loanApp/urls.py
from django.urls import path
from .views import *
from loanApp import views


app_name = 'loanApp'
urlpatterns = [
    path('loan-request/', views.LoanRequest, name='loan_request'),
    path('loan-payment/', views.LoanPayment, name='loan_payment'),
    path('user-transaction/', views.UserTransaction, name='user_transaction'),
    path('user-loan-history/', views.UserLoanHistory, name='user_loan_history'),
    path('user-dashboard/', views.UserDashboard, name='user_dashboard'),
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),

]

loan_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from loanApp import views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('account/', include('loginApp.urls')),
    path('loan/', include('loanApp.urls')),
    path('manager/', include('managerApp.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'loanApp.views.error_404_view'

loanApp/models.py
from django.db import models
from django.contrib.auth.models import User
from loginApp.models import CustomerSignUp
import uuid
from .choices import *
# Create your models here.


class loanCategory(models.Model):
    loan_name = models.CharField(max_length=250)
    creation_date = models.DateField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.loan_name


class loanRequest(models.Model):
    customer = models.ForeignKey(
        CustomerSignUp, on_delete=models.CASCADE, related_name='loan_customer')
    category = models.ForeignKey(
        loanCategory, on_delete=models.CASCADE, null=True)
    request_date = models.DateField(auto_now_add=True)
    status_date = models.CharField(
        max_length=150, null=True, blank=True, default=None)
    reason = models.TextField()
    status = models.CharField(max_length=100, default='pending')
    amount = models.PositiveIntegerField(default=0)
    year = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.customer.user.username


class CustomerLoan(models.Model):
    customer = models.ForeignKey(
        CustomerSignUp, on_delete=models.CASCADE, related_name='loan_user')
    total_loan = models.PositiveIntegerField(default=0)
    payable_loan = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.customer.user.username


class loanTransaction(models.Model):
    customer = models.ForeignKey(
        CustomerSignUp, on_delete=models.CASCADE, related_name='transaction_customer')

    transaction = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False)
    payment = models.PositiveIntegerField(default=0)
    payment_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer.user.username

class Transaction(models.Model):
    customer = models.ForeignKey(
        CustomerSignUp,
        related_name='transactions',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    balance_after_transaction = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    transaction_type = models.PositiveSmallIntegerField(
        choices=TRANSACTION_TYPE_CHOICES
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.customer.user.username)

    class Meta:
        ordering = ['timestamp']

loanApp/forms.py
import datetime
from django import forms
from django.conf import settings
from .models import Transaction, loanRequest, loanTransaction


class LoanRequestForm(forms.ModelForm):
    class Meta:
        model = loanRequest
        fields = ('category', 'reason', 'amount', 'year')


class LoanTransactionForm(forms.ModelForm):
    class Meta:
        model = loanTransaction
        fields = ('payment',)

class TransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = [
            'amount',
            'transaction_type'
        ]

    def __init__(self, *args, **kwargs):
        self.customer = kwargs.pop('customer')
        super().__init__(*args, **kwargs)

        self.fields['transaction_type'].disabled = True
        self.fields['transaction_type'].widget = forms.HiddenInput()

    def save(self, commit=True):
        self.instance.customer = self.customer
        self.instance.balance_after_transaction = self.customer.balance
        return super().save()


class DepositForm(TransactionForm):

    def clean_amount(self):
        min_deposit_amount = settings.MINIMUM_DEPOSIT_AMOUNT
        amount = self.cleaned_data.get('amount')

        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )

        return amount


class WithdrawForm(TransactionForm):

    def clean_amount(self):
        customer = self.customer
        min_withdraw_amount = settings.MINIMUM_WITHDRAWAL_AMOUNT
        max_withdraw_amount = settings.MAX_WITHDRAWAL_AMOUNT
        balance = customer.balance

        amount = self.cleaned_data.get('amount')

        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )

        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )

        if amount > balance:
            raise forms.ValidationError(
                f'You have {balance} $ in your account. '
                'You can not withdraw more than your account balance'
            )

        return amount


class TransactionDateRangeForm(forms.Form):
    daterange = forms.CharField(required=False)

    def clean_daterange(self):
        daterange = self.cleaned_data.get("daterange")
        print(daterange)

        try:
            daterange = daterange.split(' - ')
            print(daterange)
            if len(daterange) == 2:
                for date in daterange:
                    datetime.datetime.strptime(date, '%Y-%m-%d')
                return daterange
            else:
                raise forms.ValidationError("Please select a date range.")
        except (ValueError, AttributeError):
            raise forms.ValidationError("Invalid date range")

loanApp/views.py
from datetime import timezone
from decimal import Decimal
import decimal
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from loanApp.choices import DEPOSIT, WITHDRAWAL
from loginApp.models import CustomerSignUp
from .forms import DepositForm, LoanRequestForm, LoanTransactionForm, TransactionDateRangeForm, WithdrawForm
from .models import Transaction, loanRequest, loanTransaction, CustomerLoan
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from dateutil.relativedelta import relativedelta
from django.db.models import Sum
# Create your views here.


# @login_required(login_url='/account/login-customer')
def home(request):

    return render(request, 'home.html', context={})


@login_required(login_url='/account/login-customer')
def LoanRequest(request):

    form = LoanRequestForm()

    if request.method == 'POST':
        form = LoanRequestForm(request.POST)

        if form.is_valid():
            loan_obj = form.save(commit=False)
            loan_obj.customer = request.user.customer
            loan_obj.save()
            return redirect('/')

    return render(request, 'loanApp/loanrequest.html', context={'form': form})

    # reason = request.POST.get('reason')
    # amount = request.POST.get('amount')
    # category = request.POST.get('category')
    # year = request.POST.get('year')
    # customer = request.user.customer

    # loan_request = LoanRequest(request)
    # loan_request.customer = customer
    # loan_request.save()
    # if form.is_valid():
    #     loan_request = form.save(commit=False)
    #     loan_request.customer = request.user.customer
    #     print(loan_request)
    #     return redirect('/')


@login_required(login_url='/account/login-customer')
def LoanPayment(request):
    form = LoanTransactionForm()
    if request.method == 'POST':
        form = LoanTransactionForm(request.POST)
        if form.is_valid():
            payment = form.save(commit=False)
            payment.customer = request.user.customer
            payment.save()
            # request.user.customer.balance=decimal.Decimal(request.user.customer.balance)
            # request.user.customer.balance -=payment
            # request.user.customer.save()

            # pay_save = loanTransaction()
            return redirect('/')

    return render(request, 'loanApp/payment.html', context={'form': form})


@login_required(login_url='/account/login-customer')
def UserTransaction(request):
    transactions = loanTransaction.objects.filter(
        customer=request.user.customer)
    return render(request, 'loanApp/user_transaction.html', context={'transactions': transactions})


@login_required(login_url='/account/login-customer')
def UserLoanHistory(request):
    loans = loanRequest.objects.filter(
        customer=request.user.customer)
    return render(request, 'loanApp/user_loan_history.html', context={'loans': loans})


@login_required(login_url='/account/login-customer')
def UserDashboard(request):

    
    requestLoan = loanRequest.objects.all().filter(
        customer=request.user.customer).count(),
    approved = loanRequest.objects.all().filter(
        customer=request.user.customer).filter(status='approved').count(),
    rejected = loanRequest.objects.all().filter(
        customer=request.user.customer).filter(status='rejected').count(),
    totalLoan = CustomerLoan.objects.filter(customer=request.user.customer).aggregate(Sum('total_loan'))[
        'total_loan__sum'],
    totalPayable = CustomerLoan.objects.filter(customer=request.user.customer).aggregate(
        Sum('payable_loan'))['payable_loan__sum'],
    totalPaid = loanTransaction.objects.filter(customer=request.user.customer).aggregate(Sum('payment'))[
        'payment__sum'],
    

    dict = {
        
        'request': requestLoan[0],
        'approved': approved[0],
        'rejected': rejected[0],
        'totalLoan': totalLoan[0],
        'totalPayable': totalPayable[0],
        'totalPaid': totalPaid[0],
        

    }

    return render(request, 'loanApp/user_dashboard.html', context=dict)


class TransactionRepostView(LoginRequiredMixin, ListView):
    template_name = 'transactions/transaction_list.html'
    model = Transaction
    form_data = {}

    def get(self, request, *args, **kwargs):
        form = TransactionDateRangeForm(request.GET or None)
        if form.is_valid():
            self.form_data = form.cleaned_data

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            customer=self.request.user.customer
        )

        daterange = self.form_data.get("daterange")

        if daterange:
            queryset = queryset.filter(timestamp__date__range=daterange)

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'customer': self.request.user.customer,
            'form': TransactionDateRangeForm(self.request.GET or None)
        })

        return context


class TransactionCreateMixin(LoginRequiredMixin, CreateView):
    template_name = 'loanApp/transaction_form.html'
    model = Transaction
    title = ''
    success_url = reverse_lazy('loanApp:transaction_report')
   

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'customer': self.request.user.customer
        })
        
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })

        return context


class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit Money to Your Account'

    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')
        customer = self.request.user.customer

      

        customer.balance += amount
        customer.save(
            update_fields=[
                
                'balance'
            ]
        )

        messages.success(
            self.request,
            f'{amount}$ was deposited to your account successfully'
        )
        print(f'{amount}$ was deposited to your account successfully')
        print(customer.balance)
        return super().form_valid(form)


class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money from Your Account'

    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial

    def form_valid(self, form):
        amount = form.cleaned_data.get('amount')

        self.request.user.customer.balance -= form.cleaned_data.get('amount')
        self.request.user.customer.save(update_fields=['balance'])

        messages.success(
            self.request,
            f'Successfully withdrawn {amount}$ from your account'
        )

        return super().form_valid(form)

def error_404_view(request, exception):
    print("not found")
    return render(request, 'notFound.html')

templates/loanApp/loanrequest.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title_block %}
Loan Request
{% endblock %}


{% block body_block %}

{% include 'navbar.html' %}
<div class="container my-5">

    <div class="row mb-5">
        <div class="p-5 m-auto rounded shadow-lg col-md-6 bg-body">
            <h3 class="text-center text-success">درخواست وام</h3>
            </h3>
            <form method="POST" class="my-5">

                {% csrf_token %}


                <div class="mb-4 input-group">
                    <div class="input-group-text">نوغ وام</div>
                    {% render_field form.category|attr:'required:true' class="form-control" %}
                </div>




                <div class="mb-4 form-outline">

                    {% render_field form.reason|attr:'required:true' class="form-control" %}
                    <label class="form-label">توضیحات</label>
                </div>

                <div class="mb-4 form-outline">

                    {% render_field form.amount|attr:'required:true' type="number" class="form-control" %}
                    <label class="form-label">مبلغ درخواستی</label>
                </div>



                <div class="mb-4 form-outline">

                    {% render_field form.year|attr:'required:true' type="number" class="form-control" %}
                    <label class="form-label">How many year for loan?</label>
                </div>

                <!-- 2 column grid layout for inline styling -->
                <div class="mb-4 row ">
                    <div class="col">
                        <!-- Checkbox -->
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" checked />
                            <label class="form-check-label"> Remember me </label>
                        </div>
                    </div>


                </div>

                <button type="submit" class="mb-4 btn btn-primary btn-block">Send Request</button>




            </form>
        </div>
    </div>





</div>

{% include "footer.html" %}

{% endblock %}

templates/loanApp/payment.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title_block %}
پرداخت قسط وام
{% endblock %}


{% block body_block %}

{% include 'navbar.html' %}
<div class="container my-5">

    <div class="row">
        <div class="p-5 m-auto rounded shadow-lg col-md-4 bg-body">
            <h3 class="text-center text-success">{{user}} </h3>
            <form method="POST" class="my-5">

                {% csrf_token %}



                <div class="mb-4 form-outline">

                    {% render_field form.payment|attr:'required:true' class="form-control" %}
                    <label class="form-label">پرداخت هزینه</label>
                </div>

                <button type="submit" class="mb-4 btn btn-primary btn-block">پرداخت</button>



        </div>

        <!-- Submit button -->

        <!-- Register buttons -->




        </form>
    </div>
</div>





</div>

{% include "footer.html" %}

{% endblock %}

templates/loanApp/transaction_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title_block %}
تراکنش
{% endblock %}


{% block body_block %}

{% include 'navbar.html' %}

{% block content %}
<div class="container my-5">

    <div class="row">
        <div class="p-5 m-auto rounded shadow-lg col-md-4 bg-body">
            <h3 class="text-center text-success">{{user}} </h3>
            <form method="POST" class="my-5">
        {% csrf_token %}

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                قیمت
            </label>
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
        </div>
        {% if form.amount.errors %}
            {% for error in form.amount.errors %}
                <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <button type="submit" class="mb-4 btn btn-primary btn-block">ثبت</button>
    </form>
</div>
{% endblock %}

{% endblock %}

templates/loanApp/transaction_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title_block %}
موجودی
{% endblock %}


{% block body_block %}
{% block head_extra %}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% include 'navbar.html' %}

{% block content %}
<form method="get">
    <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative">
        <input type="search" name="daterange" id="search" placeholder="Filter using date range" value="{{ request.GET.daterange }}" class="appearance-none w-full outline-none focus:outline-none active:outline-none" />
        <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
        </button>
    </div>
    {% if form.daterange.errors %}
        {% for error in form.daterange.errors %}
            <p class="text-red-600 text-sm italic">{{ error }}</p>
        {% endfor %}
    {% endif %}
</form>


<div class="container my-5">
    <h3 class="text-center text-primary">شارژ یا برداشت از حساب</h3>
    <div class="my-5 users main-section">
    <table class="table text-center table-light table-hover table-bordered table-striped">
        <thead class="bg-dark ">
        <tr class="text-dark ">
            <th scope="col">نوع تراکنش</th>
            <th scope="col">تاریخ</th>
            <th scope="col">قیمت</th>
            <th scope="col">موجودی بعد از تراکنش</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr >
            <td class="border px-4 py-2 text-center">{{ transaction.get_transaction_type_display }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.timestamp }}</td>
            <td class="border px-4 py-2 text-center"> {{ transaction.amount }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.balance_after_transaction }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
        
            <h6 class="border px-4 py-2 text-center" >{{ customer.balance }}:مانده حساب</h6>
            
        
        
    
    </div>
    

            {% endblock %}

            {% endblock %}

templates/loanApp/transaction_report.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title_block %}
User Login
{% endblock %}


{% block body_block %}



{% block head_extra %}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block content %}
    <h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Transaction Report</h1>
    <hr />
    <form method="get">
        <div class="mt-10 h-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative">
            <input type="search" name="daterange" id="search" placeholder="Filter using date range" value="{{ request.GET.daterange }}" class="appearance-none w-full outline-none focus:outline-none active:outline-none" />
            <button type="submit" class="ml-1 outline-none focus:outline-none active:outline-none">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-6 h-6">
                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
                </svg>
            </button>
        </div>
        {% if form.daterange.errors %}
            {% for error in form.daterange.errors %}
                <p class="text-red-600 text-sm italic">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </form>
    <table class="table-auto mx-auto w-full mt-8">
        <thead class="bg-gray-800 text-white">
        <tr class="uppercase font-semibold text-sm">
            <th class="px-4 py-2">Transaction Type</th>
            <th class="px-4 py-2">Date</th>
            <th class="px-4 py-2">Amount</th>
            <th class="px-4 py-2">Balance After Transaction</th>
        </tr>
        </thead>
        <tbody>
        {% for transaction in object_list %}
        <tr class="{% cycle 'bg-gray-300' 'bg-white-100' %}">
            <td class="border px-4 py-2 text-center">{{ transaction.get_transaction_type_display }}</td>
            <td class="border px-4 py-2 text-center">{{ transaction.timestamp }}</td>
            <td class="border px-4 py-2 text-center">$ {{ transaction.amount }}</td>
            <td class="border px-4 py-2 text-center">$ {{ transaction.balance_after_transaction }}</td>
        </tr>
        {% endfor %}
        <tr class="bg-gray-600 text-white">
            <th class="px-4 py-2 text-right" colspan="3">Final Balance</th>
            <th class="px-4 py-2 text-center">$ {{ customer.balance }}</th>
        </tr>
        </tbody>
    </table>
{% endblock %}


{% endblock %}

templates/loanApp/user_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% block css_block %}
<style>
    #second-part {
        margin: auto;
    }


    .status {
        border-radius: 10px;
        color: white;
        margin: 10px 20px;
        padding: 20px;
    }

    .deposit {

        background-color: slateblue;
    }

    .withdraw {

        background-color: lightsalmon;

    }

    .balance {

        background-color: rgb(231, 198, 6);
    }

    #digit {
        font-size: 60px;
        font-weight: bold;
        text-align: end;
    }

    .common-section {
        padding: 30px;
        margin: 50px 20px;
        box-shadow: 0 0 10px;
        border-radius: 10px;
    }
</style>
{% endblock %}


{% block body_block %}
{% include 'navbar.html' %}
<div class="container p-5 my-5">
    <div class="p-5 m-4 text-center alert alert-primary" role="alert">
        <h1>پنل کاربری</h1>
    </div>
    <div id="second-part">
        <div class="row">
            
            <div class="col-md-4">
                <div class="withdraw status">
                    <h3>درخواست وام های تایید نشده </h3>
                    <h1> <span id='digit'>{{request}}</span> </h1>
                </div>

            </div>
           
            <div class="col-md-4 ">
                <div class="bg-info status">
                    <h3>درخواست وام های تایید شده</h3>
                    <h1><span id="digit">{{approved}}</span>

                    </h1>
                </div>

            </div>
            <div class="col-md-4 ">
                <div class="status" style="background-color:#95CEFF">
                    <h3>درخواست های رد شده</h3>
                    <h1><span id="digit">{{rejected}}</span></h1>
                </div>

            </div>
            <div class="col-md-4 ">
                <div class="status" style="background-color:#90ED7D">
                    <h3>مجموع وام پرداخت نشده</h3>

                    {% if totalPayable %}
                    <h1><span id="digit">৳{{ totalPayable|sub:0 }}</span></h1>
                    {% else %}
                    <h1><span id="digit">৳0</span></h1>
                    {% endif %}
                </div>

            </div>
            <div class="col-md-4 ">
                <div class="status" style="background-color:#FF7599">
                    <h3>مجموع وام های تایید شده </h3>

                    {% if totalLoan %}
                    <h1><span id="digit">৳{{totalLoan|sub:0}}</span></h1>
                    {% else %}
                    <h1><span id="digit">৳0</span></h1>
                    {% endif %}
                </div>

            </div>
            <div class="col-md-4 ">
                <div class="status" style="background-color:#EF5350">
                    <h3>مجموع وام های پرداخت شده </h3>
                    {% if totalPaid %}
                    <h1><span id="digit">৳{{totalPaid|sub:0}}</span></h1>
                    {% else %}
                    <h1><span id="digit">৳0</span></h1>
                    {% endif %}
                </div>

            </div>

            <div class="col-md-4 ">
                <div class="status" style="background-color:#42A5F5">
                    <h3>Total Due Loan</h3>

                    {% if totalPayable or totalPaid %}
                    <h1><span id="digit">৳{{ totalPayable|sub:totalPaid }}</span></h1>
                    {% else %}
                    <h1><span id="digit">৳0</span></h1>
                    {% endif %}
                </div>

            </div>
        </div>

    </div>
</div>

{% include 'footer.html' %}

{% endblock %}

templates/loanApp/user_loan_history.html
{% extends 'base.html' %}

{% load static %}


{% block block_js %}
<script>

</script>
{% endblock %}


{% block css_block %}
<style>

</style>

{% endblock %}

{% block body_block %}
{% include 'navbar.html' %}
<div class="container my-5">
    <h1 class="text-center text-primary">Loan Request History</h1>
    <div class="my-5 users">



        <table class="table text-center table-light table-hover table-bordered table-striped">
            <thead class="bg-dark ">
                <tr class="text-dark ">
                    <th scope="col">SL</th>
                    <th scope="col">Loan ID</th>
                    <th scope="col">User ID</th>
                    <th scope="col">Username</th>
                    <th scope="col">Status</th>
                    <th scope="col">Category</th>
                    <th scope="col">Request Amount</th>
                    <th scope="col">Request Date</th>
                    <th scope="col">Year</th>
                    <th scope="col">Email</th>


                </tr>
            </thead>
            <tbody>
                {% for loan in loans %}

                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{loan.id}}</td>
                    <td>{{loan.customer.id}}</td>
                    <td>{{loan}}</td>
                    <td>
                        <button type="button" class="px-3 text-white btn btn-info btn-sm">
                            {{loan.status}}
                        </button>
                    </td>
                    <!-- <td> <img src="/media/{{user.profile_picture}}" alt="Profile Pic" height="40px" width="40px" />
                    </td> -->
                    <td>{{loan.category}}</td>
                    <td>{{loan.amount}} Tk</td>
                    <td>{{loan.request_date}}</td>
                    <td>{{loan.year}}</td>
                    <td>{{loan.customer.user.email}}</td>



                </tr>
                {% endfor %}

            </tbody>

        </table>





    </div>



</div>

{% include 'footer.html'%}
{% endblock %}

templates/loanApp/user_transaction.html
{% extends 'base.html' %}

{% load static %}





{% block css_block %}
<style>
    .main-section {
        margin-bottom: 500px;
    }
</style>

{% endblock %}

{% block body_block %}

{% include 'navbar.html' %}
<div class="container my-5 ">
    <h1 class="text-center text-primary">تراکنش ها</h1>
    <div class="my-5 users main-section">



        <table class="table text-center table-light table-hover table-bordered table-striped">
            <thead class="bg-dark ">
                <tr class="text-dark ">
                    <th scope="col">SL</th>

                    <th scope="col">User ID</th>
                    <th scope="col">Username</th>

                    <th scope="col">Payment Amount</th>
                    <th scope="col">Transaction ID</th>
                    <th scope="col">Date</th>

                    <th scope="col">Customer Email</th>


                </tr>
            </thead>
            <tbody>
                {% for loan in transactions %}

                <tr>
                    <th scope="row">{{forloop.counter}}</th>

                    <td>{{loan.customer.id}}</td>
                    <td>{{loan.customer}}</td>


                    <td>{{loan.payment}} </td>
                    <td>{{loan.transaction}}</td>
                    <td>{{loan.payment_date}}</td>
                    <td>{{loan.customer.user.email}}</td>


                </tr>
                {% endfor %}

            </tbody>

        </table>





    </div>



</div>

{% include 'footer.html' %}

{% endblock %}